[project]
name = "autoscraper-alirezamika"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

# Add license information:
license = { name = "MIT", text = "MIT License text goes here." }
